#!/bin/sh

if ! command -v python > /dev/null; then
    echo "please install python3: https://www.python.org/downloads/"
    exit 1
fi

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

. venv/bin/activate

pip install -r requirements.txt

python3 website/manage.py runserver

exit 0

