#!/bin/sh

if ! command -v python > /dev/null; then
    echo "please install python3: https://www.python.org/downloads/"
    exit 1
fi

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

. venv/bin/activate

pip install -r requirements.txt

if [ ! -f "website/website/local_settings.py" ]; then
    echo "DJANGO_SECRET_KEY='PleaseChangeMe'" > website/website/local_settings.py

    SECRET_KEY=$(python3 website/manage.py shell -c "
from django.core.management.utils import get_random_secret_key
print(get_random_secret_key())
")

    echo "DJANGO_SECRET_KEY='${SECRET_KEY}'" > website/website/local_settings.py

fi


python3 website/manage.py runserver

rm -f /var/tmp/django_cache/*.djcache

exit 0

